### ISSUE TITLE
After Integration with next js - getting error on build time ReferenceError: CLIENT_SCRIPTS_BY_PATH is not defined

### ISSUE THREAD

**Issue by gauravverma029** [amannn/next-client-script#11]
![Screen Shot 2020-09-29 at 14 06 31](https://user-images.githubusercontent.com/4488516/94556308-27ed2880-025d-11eb-82a8-9ac7cc3a4742.png)

**Comment by amannn** [comment]
Thanks for your report! Can you please provide a reproduction repository?

Please also note the compatibility hints of this plugin: https://github.com/amannn/next-client-script#compatibility

**Comment by amannn** [comment]
I'll close this due to inactivity. Feel free to open a new issue with a reproduction if this problem still exists.
