### ISSUE TITLE
With next-compose-plugins 

### ISSUE THREAD

**Issue by Sangdt** [amannn/next-client-script#16]
It's seems like the library does not working with next-compose-plugins.
 
Config like below will throw error CLIENT_SCRIPTS_BY_PATH is not defined in dev. 
```
module.exports = withPlugins([
  [withBundleAnalyzer],
  [withClientScripts,{
    '/':'./Helper/clientScripts/index.js'
  }],
nextConfig);
```

Nextjs version: 10.0.5

**Comment by amannn** [comment]
Thanks for the report! I haven't used `next-compose-plugins` yet. Would you be interested in looking into the way it composes the plugins and contributing a PR?

**Comment by Sangdt** [comment]
well i did manage to get working, here are the configs:
```
module.exports = withPlugins([
  [withBundleAnalyzer],
  withClientScripts({
    '/': './Helper/clientScripts/index.js'
  }),
  [withPWA, {
    pwa: {
      disable: process.env.NODE_ENV !== "production",
      register: true,
      dest: 'public',
      // scope: '/app',
      // sw: 'worker.js',
      // importScripts: ['/customWorker.js'],
      // runtimeCaching
      //...
    }
  }]
], nextConfig);
```

**Comment by amannn** [comment]
Good to hear, thank you for posting your solution!
